 Load in NumPy
 

In [2]:
import numpy as np

The Basics - Getting started



In [4]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
#Get dimensions
a.ndim

1

In [8]:
#Get dimensions
b.ndim

2