 Load in NumPy
 

In [22]:
import numpy as np

The Basics - Getting started



In [23]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [24]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [25]:
#Get dimensions
a.ndim

1

In [26]:
#Get dimensions
b.ndim

2

In [27]:
#Get shape
b.shape

(2, 3)

In [28]:
#Get Type
a.dtype

dtype('int64')

In [29]:
#Get size in bytes
a.itemsize  

8

In [30]:
#Get total size in bytes
a.itemsize * a.size

24